### PR TITLE
feat: argo ip

### PR DESCRIPTION
**Pull request by Kurichi**

### CODE REVIEW

**Comment by Kurichi** [comment]
atlantis plan

**Comment by Kurichi** [comment]
atlantis plan

**Comment by Kurichi** [comment]
atlantis plan

**Comment by Kurichi** [comment]
atlantis apply

**Comment by ghost** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `infra/terraform/environment/prod` workspace: `default`

**Pull request merged**
